name: Deploy Development

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # https://github.com/marketplace/actions/dokku-deploy-action?version=v1
    - name: Push to medusa
      uses: idoberko2/dokku-deploy-github-action@v1
      with:
        ssh-private-key: ${{ secrets.MEDUSA_GLOBAL_DEPLOY_KEY }}
        dokku-user: 'dokku'
        remote-branch: 'master'
        git-push-flags: '--force'
        dokku-host: 'medusa.datasektionen.se'
        app-name: 'darkmode'